<$PLAN9/src/mkhdr

TARG=nc
HFILES=a.h
OFILES=\
	main.$O			\
	help.$O			\
	actionbar.$O	\
	dirview.$O		\
	dirviewcmd.$O	\
	dirmodel.$O		\
	dirpanel.$O		\
	viewercmd.$O	\
	text.$O			\
	message.$O		\
	input.$O		\
	glob.$O			\
	fops.$O			\
	utils.$O

<$PLAN9/src/mkone
